### ISSUE TITLE
Move into create-t3-app

### ISSUE THREAD

**Issue by juliusmarminge** [kroucher/create-t3-app-docs#1]
Would boost interest and get the community more involved if this was part of the main repo.

We could split it ([create-t3-app](https://github.com/create-t3-app)), up into `docs` and `cli`.

What'ya think? @kroucher @nexxeln

**Comment by kroucher** [comment]
Absolutely, let me know if you want me to transfer the repo or if you guys are happy to fork it 👍

**Comment by kroucher** [comment]
> Would boost interest and get the community more involved if this was part of the main repo.
> 
> We could split it ([create-t3-app](https://github.com/create-t3-app)), up into `docs` and `cli`.
> 
> What'ya think? @kroucher @nexxeln

Absolutely, let me know if you want me to transfer the repo or if you guys are happy to fork it 👍

**Comment by juliusmarminge** [comment]
Feel free to PR the source into a `docs` subfolder 👍

**Comment by nexxeln** [comment]
I think then there's no use for this repo anymore if we do this.

**Comment by juliusmarminge** [comment]
> I think then there's no use for this repo anymore if we do this.

Yea my idea was to bring everything to one place which I think would encourage contributors to contribute to all the pieces 👍 

Almost every package has their docs site in the same repo as the package itself.

**Comment by kroucher** [comment]
I don't mind if it's in the main repo, create.t3.gg or as a third option I can just transfer ownership of this repo to t3-oss - I agree that having docs in the main org will likely bring more attention and PRs for contribution. 

Also wondering if it's worth writing the docs on tRPC as though v10 is already out, save having to redo a bunch of stuff
